---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    name: CI

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc

      - name: CI
        run: npm run dist

      - name: Check if build left artifacts
        run: git diff --exit-code --ignore-space-at-eol
