---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: echo "nodeVersion=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
        id: nvm
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ steps.nvm.outputs.nodeVersion }}
      - run: npm run dist
      - run: git diff --exit-code --ignore-space-at-eol
