---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "nodeVersion=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
        id: nvm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.nodeVersion }}
      - run: npm run dist
      - run: git diff --exit-code --ignore-space-at-eol
