---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: echo "nodeVersion=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
        id: nvm
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ steps.nvm.outputs.nodeVersion }}
      - run: npm run dist
      - run: git diff --exit-code --ignore-space-at-eol
